### ISSUE TITLE
Undefined symbol when importing ATK.Core Python module

### ISSUE THREAD

**Issue by SpotlightKid** [mbrucher/AudioTK#6]
```
>>> import ATK.Core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/ATK/Core/__init__.py", line 2, in <module>
    from .Core import *
  File "/usr/lib/python3.5/site-packages/ATK/Core/Core.py", line 30, in <module>
    _Core = swig_import_helper()
  File "/usr/lib/python3.5/site-packages/ATK/Core/Core.py", line 26, in swig_import_helper
    _mod = imp.load_module('_Core', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/python3.5/site-packages/ATK/Core/_Core.so: undefined symbol: _ZN3ATK16OutPointerFilterIxEC1EPxilb
```

Note: I moved `/usr/lib/site-packages/ATK` to `/usr/lib/python3.5/site-packages` since `/usr/lib/site-packages` is not a valid Python module directory on non-debian-based systems.

**Comment by mbrucher** [comment]
That's intriguing. I'll try to reproduce the issue.
You can set the Python specific folder by using PYTHON_INSTALL_FOLDER

**Comment by mbrucher** [comment]
OK, I guess the issue is with the differences between long and long long on Linux. I should be able to do something better now.

**Comment by mbrucher** [comment]
Let's say this is closed until proven otherwise ;)
If it compiles, now it should be OK, as the SWIG wrappers explicitly uses the same types as the C++ instantiations.

**Comment by SpotlightKid** [comment]
Yes, this seems to have fixed the issue.
